<template>
  <v-layout row wrap>
    <v-flex xs8>
      
      <v-layout row align-center>
        <v-flex xs4>
          <v-subheader>Branch Name</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field v-model="accountData.branchName" required :disabled="disableEdit"></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row align-center>
        <v-flex xs4>
          <v-subheader>Franchise Application Approval Date</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-menu
            ref="menu"
            v-model="menu"
            :close-on-content-click="false"
            :nudge-right="40"
            :disabled="disableEdit"
            transition="scale-transition"
            offset-y
            full-width
            max-width="290px"
            min-width="290px"
          >
            <template v-slot:activator="{ on }">
              <v-text-field
                :value="vDateFormatter(accountData.approvedDate)"
                prepend-inner-icon="event"
                :disabled="disableEdit"
                readonly
                v-on="on"
              ></v-text-field>
            </template>
            <v-date-picker
              v-model="accountData.approvedDate"
              @change="menu = false"
              :disabled="disableEdit"
              no-title
            ></v-date-picker>
          </v-menu>
        </v-flex>
      </v-layout>
      
      <v-layout row align-center>
        <v-flex xs4>
          <v-subheader>Branch Opening Date</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-menu
            ref="menu"
            v-model="menu2"
            :close-on-content-click="false"
            :nudge-right="40"
            :disabled="disableEdit"
            transition="scale-transition"
            offset-y
            full-width
            max-width="290px"
            min-width="290px"
          >
            <template v-slot:activator="{ on }">
              <v-text-field
                :value="vDateFormatter(accountData.establishDate)"
                prepend-inner-icon="event"
                :disabled="disableEdit"
                readonly
                v-on="on"
              ></v-text-field>
            </template>
            <v-date-picker
              v-model="accountData.establishDate"
              @change="menu2 = false"
              :disabled="disableEdit"
              no-title
            ></v-date-picker>
          </v-menu>
        </v-flex>
      </v-layout>

      <!-- <v-layout row align-center>
        <v-flex xs4>
          <v-subheader>Branch Manager Name</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field 
            v-model="accountData.managersName" 
            :disabled="disableEdit"
          ></v-text-field>
        </v-flex>
      </v-layout> -->

      <v-layout row>
        <v-flex xs4>
          <v-subheader>Branch Manager's First Name</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field v-model="accountData.firstName" :disabled="disableEdit"></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>Branch Manager's Middle Name</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field v-model="accountData.middleInitial" :disabled="disableEdit"></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>Branch Manager's Last Name</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field v-model="accountData.lastName" :disabled="disableEdit"></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row v-if="!accountData.isEmailAutogenerated" align-center>
        <v-flex xs4>
          <v-subheader>Email Address</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field 
            v-model="accountData.email" 
            :disabled="disableEdit"
            type="email"
          ></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row align-center>
        <v-flex xs4>
          <v-subheader>Mobile Number</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field 
            v-model="accountData.contact" 
            :disabled="disableEdit"
            type="number"
          ></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row align-center>
        <v-flex xs4>
          <v-subheader>Lot Number / Bldg.</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field v-model="accountData.address.house" :disabled="disableEdit"></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row align-center>
        <v-flex xs4>
          <v-subheader>Street Name</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field
            v-model="accountData.address.streetName"
            :disabled="disableEdit"
          ></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row align-center>
        <v-flex xs4>
          <v-subheader>City/Municipality</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field
            v-model="accountData.address.citymun"
            :disabled="disableEdit"
          ></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row align-center>
        <v-flex xs4>
          <v-subheader>Province</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field
            v-model="accountData.address.province"
            :disabled="disableEdit"
          ></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row align-center>
        <v-flex xs4>
          <v-subheader>Zip Code</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field
            v-model="accountData.address.zipCode"
            :disabled="disableEdit"
          ></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row align-center>
        <v-flex xs4>
          <v-subheader>Branch's Delivery Fee</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field
            v-model="accountData.address.deliveryFee"
            prefix="₱"
            type="number"
            :disabled="disableEdit"
          ></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row v-if="accountData.social" align-center>
        <v-flex xs4>
          <v-subheader>Facebook</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field
            v-model="accountData.social.facebook"
            :disabled="disableEdit"
          ></v-text-field>
        </v-flex>
      </v-layout>
      <v-layout row align-center>
        <v-flex xs4>
          <v-subheader>Branch ID</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field
            v-model="accountData.agentId"
            disabled
          ></v-text-field>
        </v-flex>
      </v-layout>
    </v-flex>

    <v-flex xs1></v-flex>

    <v-flex xs3>
      <div class="text-xs-center">
        <v-card>
          <v-card-title class="title">
            Branch Picture
          </v-card-title>
          <v-divider></v-divider>
          <v-card-text>
            <v-avatar tile size="200">
              <v-img
                :src="accountData.downloadURL"
                :lazy-src="userPlaceholder"
                v-if="accountData.downloadURL"
              >
                <v-layout
                  slot="placeholder"
                  fill-height
                  align-center
                  justify-center
                  ma-0
                >
                  <v-progress-circular
                    indeterminate
                    color="grey lighten-5"
                  ></v-progress-circular>
                </v-layout>
              </v-img>
              <v-img :src="userPlaceholder" :lazy-src="userPlaceholder" v-else>
                <!-- <v-layout
                  slot="placeholder"
                  fill-height
                  align-center
                  justify-center
                  ma-0
                >
                  <v-progress-circular
                    indeterminate
                    color="grey lighten-5"
                  ></v-progress-circular>
                </v-layout> -->
              </v-img>

              <v-btn
                v-if="!disableEdit"
                class="overlayImage"
                @click="uploadPicDialog = true"
                depressed color="primary" dark small
              >
                <v-icon small class="mr-1">camera_alt</v-icon>
                REPLACE PHOTO
              </v-btn>
            </v-avatar>
          </v-card-text>
        </v-card>
      </div>
      <div class="mt-4">
        <v-btn
          v-show="disableEdit"
          color="orange darken-2"
          dark block class="mt-2"
          @click="resendEmailVerification"
          :loading="resendEmailBtn"
        >RESEND EMAIL VERIFICATION
        </v-btn>
      </div>
      <div class="mt-2" v-if="disableEdit">
        <v-btn 
          color="green darken-2" block
          dark @click="editForm"
        >EDIT DETAILS
        </v-btn>
      </div>
      <div v-else class="mt-2">
        <v-btn
          color="green darken-2"
          dark block
          @click="updateBranch"
          :loading="updateLoadingBtn"
        >SAVE CHANGES
        </v-btn>
        <v-btn
          color="red darken-1"
          dark block outline class="mt-2"
          @click="resetForm"
          :loading="updateLoadingBtn"
        >CANCEL
        </v-btn>
      </div>
      <div class="mt-6" v-if="disableEdit">
        <v-btn
          color="red darken-2"
          dark block
          @click="deleteBranch"
          :loading="deleteBranchBtn"
        >DELETE BRANCH
        </v-btn>
      </div>
    </v-flex>

    <v-dialog v-model="uploadPicDialog" persistent width="350px">
      <v-card>
        <v-card-title class="primary white--text font-weight-bold subheading">
          <span v-if="!accountData.downloadURL">ADD BRANCH PIC</span>
          <span v-else>REPLACE BRANCH PIC</span>
          <v-spacer></v-spacer>
          <v-btn icon medium @click="closeUploadDialog">
            <v-icon color="white" medium>close</v-icon>
          </v-btn>
        </v-card-title>
        <v-container align-center>
          <v-layout align-center justify-start wrap row>
            <v-flex xs12>
              <div class="text-xs-left font-weight-bold">Upload a Branch Pic / Pic of Branch Manager</div>
            </v-flex>
            <v-flex xs10 mt-4>
              <input
                type="file"
                ref="branchPic"
                value="upload"
                accept=".png, .jpg, .jpeg"
                @change="validateFile"
              />
            </v-flex>
          </v-layout>
        </v-container>
        <v-card-actions>
          <v-spacer></v-spacer>
          <v-btn outline color="black" 
            :loading="uploadPicBtn" 
            @click="closeUploadDialog"
          >CANCEL
          </v-btn>
          <v-btn dark depressed color="primary" 
            :loading="uploadPicBtn"
            @click="uploadBranchPic"
          >UPLOAD
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
    
  </v-layout>
</template>

<script>
// import userPlaceholder from "@/assets/placeholder.png";
import userPlaceholder from "@/assets/DefaultBranchPic.png";
import moment from 'moment';
import mixins from "@/mixins";
import { AUTH, STORAGE } from "@/config/firebase";

export default {
  props: ["account"],
  created() {
    this.accountData = Object.assign({}, this.account);
    //format dates into a readable format that v-date-picker could understand
    this.accountData.approvedDate = this.accountData.approvedDate ? moment(new Date(this.accountData.approvedDate)).format("YYYY-MM-DD") : null;
    this.accountData.establishDate = this.accountData.establishDate ? moment(new Date(this.accountData.establishDate)).format("YYYY-MM-DD") : null;
     
  },

  data: () => ({
    dialog: false,
    disableEdit: true,
    accountData: {},
    previousDetails: {},

    date: false,
    menu: false,
    menu2: false,

    updateLoadingBtn: false,
    resendEmailBtn: false,
    uploadPicDialog: false,
    uploadPicBtn: false,
    deleteBranchBtn: false,
  }),
  computed: {
    userPlaceholder() {
      return userPlaceholder || "";
    },
    user() {
      return this.$store.getters['auth/GET_USER'];
    }
  },
  mixins: [mixins],
  methods: {
    show() {
      this.dialog = true;
    },
    
    vDateFormatter(date) {
      return date ? moment(new Date(date)).format('DD-MMM-YYYY') : null;
    },
    
    showFullName(account) {
      const { firstName, middleInitial, lastName } = account;
      let completeName = middleInitial ? `${firstName} ${middleInitial}. ${lastName}` : `${firstName} ${middleInitial} ${lastName}`; 
      return completeName;
    },
    
    editForm() {
      this.previousDetails = Object.assign({}, this.accountData);
      this.disableEdit = false;
    },
    
    resetForm() {
      this.accountData = Object.assign({}, this.previousDetails);
      this.disableEdit = true;
    },
    
    closeUploadDialog() {
      this.uploadPicDialog = false;
      this.$refs.branchPic.value = "";
    },
    
    async resendEmailVerification() {
      console.log('resending email verification...');
      this.resendEmailBtn = true;

      try {

        await this.$store.dispatch('distributors/RESEND_ACCOUNT_VERIFICATION', {
          firstName: this.accountData.firstName,
          email: this.accountData.email
        });
        console.log('email verification sent!');
        this.resendEmailBtn = false;
        this.$swal.fire({
          type: "success",
          title: "Success!",
          text: "Email Verification link was re-sent!"
        });

      } catch(error) {
        console.log(error);
        this.resendEmailBtn = false;
        this.$swal.fire({
          type: "error",
          title: "An Error Occurred!",
          text: "An error occured while sending the account verification link! Please try again later."
        });
      }

    },

    async checkAccountPassword(password) {
      try {
        const userData = await AUTH.signInWithEmailAndPassword(this.user.email, password);
        console.log('account received: ', userData);
        return userData ? null : 'Password is incorrect!';
      } catch(error) {
        console.log(error);
        return 'Password is incorrect!';
      }
    },

    async deleteBranch() {
      console.log('deleting branch...');
      this.deleteBranchBtn = true;

      const answer = await this.$swal.fire({
        title: "Confirm Branch Deletion",
        input: 'password',
        showCancelButton: true,
        confirmButtonText: "Delete Branch",
        cancelButtonText: "Cancel",
        showCloseButton: true,
        html: `enter your account password to confirm the deletion.`,
        inputValidator: async (value) => {
          if(!value) {
            return 'Please enter your account password!';
          
          } else {
            return await this.checkAccountPassword(value);
          }
        },
        
      });
      
      if (!answer.value || !answer.hasOwnProperty('value')) {
        this.deleteBranchBtn = false;
        console.log('cancelled branch deletion');
        return;
      }

      try {

        await this.$store.dispatch('distributors/DELETE_BRANCH', {
          id: this.accountData.id,
          email: this.accountData.email,
          userObj: this.accountData,
        });

        console.log('branch deleted!');
        this.deleteBranchBtn = false;
        this.$swal.fire({
          type: "success",
          title: "Success!",
          text: "Branch was deleted!"
        });

        this.$router.push({ name: "Resellers" });

      } catch(error) {
        console.log(error);
        this.deleteBranchBtn = false;
        this.$swal.fire({
          type: "error",
          title: "An Error Occurred!",
          text: "Branch cant be delete due to an error. Please try again later."
        });
      }

    },

    async updateBranch() {
      console.log('updating branch...');
      this.updateLoadingBtn = true;

      try {
        await this.$store.dispatch('distributors/UPDATE_BRANCH', {
          id: this.accountData.id,
          updatedDetails: this.accountData,
        });

        this.updateLoadingBtn = false;

        this.$swal.fire({
          type: "success",
          title: "Success!",
          text: "Branch Details has been edited!"
        });

        this.disableEdit = true;
        this.previousDetails = Object.assign({}, this.accountData);

      } catch(error) {
        this.updateLoadingBtn = false;
        console.log(error);
        this.$swal.fire({
          type: "error",
          title: "Error!",
          text: "An error occured! Please try again later."
        });
      }
    },

    validateFile(el) {
      if (!el.target.value) {
        return;
      }

      const path = el.target.value;
      const idxDot = path.lastIndexOf(".") + 1;
      const extFile = path.substr(idxDot, path.length).toLowerCase();

      const acceptedFiles = ["jpg", "jpeg", "png"];

      if (!acceptedFiles.includes(extFile)) {
        this.$refs.branchPic.value = "";
        this.$swal.fire({
          type: "error",
          title: "Error",
          text: "The uploaded file is not an image file. Please try again."
        });
      }
    },

    async uploadBranchPic() {
      this.uploadPicBtn = true;

      if(!this.$refs.branchPic.value) {
        this.uploadPicBtn = false;
        this.$swal.fire({
          type: "error",
          title: "Error",
          text: "Please choose a file first."
        });
        return;
      }

      const file = this.$refs.branchPic.files[0];
      const metadata = { contentType: file.type };

      try {
        console.log('uploading pic...');
        const snapshot = await STORAGE.ref('appsell')
          .child("profile-pictures/" + this.accountData.id)
          .put(file, metadata);
        const downloadURL = await snapshot.ref.getDownloadURL();
        
        this.accountData.downloadURL = downloadURL;
        this.previousDetails.downloadURL = downloadURL;

        console.log('updating branch details...');
        await this.$store.dispatch("distributors/UPDATE_BRANCH", {
          id: this.accountData.id,
          updatedDetails: { downloadURL: this.accountData.downloadURL },
        });

        this.uploadPicBtn = false;
        this.disableEdit = true;
        
        this.$swal.fire({
          type: "success",
          title: "Success!",
          text: "Branch Pic has been edited!"
        });
      
      } catch(error) {
        this.uploadPicBtn = false;
        console.log(error);

        this.$swal.fire({
          type: "error",
          title: "Error!",
          text: "An error occured! Please try again later."
        });
      }

      this.closeUploadDialog();
    }
  }
};
</script>

<style>

  .overlayImage {
    position: absolute;
    z-index: 1;
  }

  .swal2-container .swal2-popup {
    font-family: 'Roboto', sans-serif;
  }

  .swal2-container .swal2-modal {
    font-family: 'Roboto', sans-serif;
  }

  .swal2-container .swal2-show {
    font-family: 'Roboto', sans-serif;
  }

</style>
