<template>
  <v-layout row wrap>
    <v-flex xs8>
      <v-layout row>
        <v-flex xs4>
          <v-subheader>First Name</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field v-model="account.firstName" readonly></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>Middle Name</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field v-model="account.middleInitial" readonly></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>Last Name</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field v-model="account.lastName" readonly></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>Birthday</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field v-model="account.birthday" readonly></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row v-if="!account.isEmailAutogenerated">
        <v-flex xs4>
          <v-subheader>Email Address</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field v-model="account.email" readonly></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>Mobile Number</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field v-model="account.contact" readonly></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>Gender</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field v-model="account.gender" readonly></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>Home Address</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field v-model="account.address.house" readonly></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>Street Name</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field
            v-model="account.address.streetName"
            readonly
          ></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>City/Municipality</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field
            v-model="account.address.citymun"
            readonly
          ></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>Province</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field
            v-model="account.address.province"
            readonly
          ></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>Zip Code</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field
            v-model="account.address.zipCode"
            readonly
          ></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row v-if="account.social">
        <v-flex xs4>
          <v-subheader>Facebook</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field
            v-model="account.social.facebook"
            readonly
          ></v-text-field>
        </v-flex>
      </v-layout>
      <v-layout row>
        <v-flex xs4>
          <v-subheader>Membership ID</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field
            :rules="numberRules"
            required
            v-model="account.agentId"
            readonly
          ></v-text-field>
        </v-flex>
      </v-layout>
    </v-flex>

    <v-flex xs1></v-flex>

    <v-flex xs3>
      <div class="text-xs-center">
        <v-card>
          <v-card-title class="title">
            Profile Picture
          </v-card-title>
          <v-divider></v-divider>
          <v-card-text>
            <v-avatar tile size="200">
              <v-img
                :src="account.downloadURL"
                :lazy-src="userPlaceholder"
                v-if="account.downloadURL"
              >
                <v-layout
                  slot="placeholder"
                  fill-height
                  align-center
                  justify-center
                  ma-0
                >
                  <v-progress-circular
                    indeterminate
                    color="grey lighten-5"
                  ></v-progress-circular>
                </v-layout>
              </v-img>
              <v-img :src="userPlaceholder" :lazy-src="userPlaceholder" v-else>
                <v-layout
                  slot="placeholder"
                  fill-height
                  align-center
                  justify-center
                  ma-0
                >
                  <v-progress-circular
                    indeterminate
                    color="grey lighten-5"
                  ></v-progress-circular>
                </v-layout>
              </v-img>
            </v-avatar>
          </v-card-text>
          <v-container>
            <v-layout row wrap align-center justify-center>
              <v-flex xs12>
                <v-btn
                  color="red darken-2"
                  dark block
                  @click="deleteReseller"
                  :loading="deleteResellerBtn"
                >DELETE RESELLER
                </v-btn>
              </v-flex>
            </v-layout>
            
            <v-flex xs12 class="mt-2">
              <v-btn
                color="orange darken-2"
                dark block
                @click="resendEmailVerification"
                :loading="resendEmailBtn"
              >RESEND EMAIL VERIFICATION
              </v-btn>
            </v-flex>
          </v-container>
        </v-card>
        <div style="margin-bottom: 50px;"></div>
        <v-card>
          <v-card-title class="title">
            Proof of ID
          </v-card-title>
          <v-divider></v-divider>
          <v-card-text>
            <v-avatar tile size="200">
              <v-img
                :src="account.proofOfId"
                :lazy-src="userPlaceholder"
                v-if="account.proofOfId"
              >
                <v-layout
                  slot="placeholder"
                  fill-height
                  align-center
                  justify-center
                  ma-0
                >
                  <v-progress-circular
                    indeterminate
                    color="grey lighten-5"
                  ></v-progress-circular>
                </v-layout>
              </v-img>
              <v-img :src="userPlaceholder" :lazy-src="userPlaceholder" v-else>
                <v-layout
                  slot="placeholder"
                  fill-height
                  align-center
                  justify-center
                  ma-0
                >
                  <v-progress-circular
                    indeterminate
                    color="grey lighten-5"
                  ></v-progress-circular>
                </v-layout>
              </v-img>
            </v-avatar>
            <br />
            <v-btn @click="show" color="primary">
              Enlarge
            </v-btn>
          </v-card-text>
        </v-card>
      </div>
    </v-flex>
    <v-dialog v-model="dialog" max-width="600">
      <v-card>
        <v-img
          :src="account.proofOfId"
          :lazy-src="userPlaceholder"
          contain
          v-if="account.proofOfId"
        >
          <v-layout
            slot="placeholder"
            fill-height
            align-center
            justify-center
            ma-0
          >
            <v-progress-circular
              indeterminate
              color="grey lighten-5"
            ></v-progress-circular>
          </v-layout>
        </v-img>
      </v-card>
    </v-dialog>
  </v-layout>
</template>

<script>
import userPlaceholder from "@/assets/placeholder.png";
import mixins from "@/mixins";
import { AUTH, STORAGE } from "@/config/firebase";

export default {
  props: ["account"],
  data: () => ({
    dialog: false,
    deleteResellerBtn: false,
    resendEmailBtn: false,
  }),
  computed: {
    userPlaceholder() {
      return userPlaceholder || "";
    },
    user() {
      return this.$store.getters['auth/GET_USER'];
    }
  },
  mixins: [mixins],
  methods: {
    show() {
      this.dialog = true;
    },

    async resendEmailVerification() {
      console.log('resending email verification...');
      this.resendEmailBtn = true;

      try {

        await this.$store.dispatch('distributors/RESEND_ACCOUNT_VERIFICATION', {
          firstName: this.account.firstName,
          email: this.account.email
        });

        console.log('email verification sent!');
        this.resendEmailBtn = false;
        this.$swal.fire({
          type: "success",
          title: "Success!",
          text: "Email Verification link was re-sent!"
        });

      } catch(error) {
        console.log(error);
        this.resendEmailBtn = false;
        this.$swal.fire({
          type: "error",
          title: "An Error Occurred!",
          text: "An error occured while sending the account verification link! Please try again later."
        });
      }

    },

    async checkAccountPassword(password) {
      try {
        const userData = await AUTH.signInWithEmailAndPassword(this.user.email, password);
        console.log('account received: ', userData);
        return userData ? null : 'Password is incorrect!';
      } catch(error) {
        console.log(error);
        return 'Password is incorrect!';
      }
    },

    async deleteReseller() {
      console.log('deleting reseller...');
      this.deleteResellerBtn = true;

      const answer = await this.$swal.fire({
        title: "Confirm Reseller Deletion",
        input: 'password',
        showCancelButton: true,
        confirmButtonText: "Delete Reseller",
        cancelButtonText: "Cancel",
        showCloseButton: true,
        html: `enter your account password to confirm the deletion.`,
        inputValidator: async (value) => {
          if(!value) {
            return 'Please enter your account password!';
          
          } else {
            return await this.checkAccountPassword(value);
          }
        },
        
      });
      
      if (!answer.value || !answer.hasOwnProperty('value')) {
        this.deleteResellerBtn = false;
        console.log('cancelled reseller deletion');
        return;
      }

      try {

        await this.$store.dispatch('distributors/DELETE_RESELLER', {
          id: this.account.id,
          email: this.account.email,
          userObj: this.account,
        });

        console.log('reseller deleted!');
        this.deleteBranchBtn = false;
        this.$swal.fire({
          type: "success",
          title: "Success!",
          text: "Reseller was deleted!"
        });

        this.$router.push({ name: "Resellers" });

      } catch(error) {
        console.log(error);
        this.deleteBranchBtn = false;
        this.$swal.fire({
          type: "error",
          title: "An Error Occurred!",
          text: "Reseller cant be delete due to an error. Please try again later."
        });
      }

    },
  }
};
</script>
