<template>
  <v-layout row wrap>
    <v-flex xs8>
      <v-layout row>
        <v-flex xs4>
          <v-subheader>First Name</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field v-model="account.firstName" readonly></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>Middle Name</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field v-model="account.middleInitial" readonly></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>Last Name</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field v-model="account.lastName" readonly></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>Birthday</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field v-model="account.birthday" readonly></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row v-if="!account.isEmailAutogenerated">
        <v-flex xs4>
          <v-subheader>Email Address</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field v-model="account.email" readonly></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>Mobile Number</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field v-model="account.contact" readonly></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>Gender</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field v-model="account.gender" readonly></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>Home Address</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field v-model="account.address.house" readonly></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>Street Name</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field
            v-model="account.address.streetName"
            readonly
          ></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>City/Municipality</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field
            v-model="account.address.citymun"
            readonly
          ></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>Province</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field
            v-model="account.address.province"
            readonly
          ></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row>
        <v-flex xs4>
          <v-subheader>Zip Code</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field
            v-model="account.address.zipCode"
            readonly
          ></v-text-field>
        </v-flex>
      </v-layout>

      <v-layout row v-if="account.social">
        <v-flex xs4>
          <v-subheader>Facebook</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field
            v-model="account.social.facebook"
            readonly
          ></v-text-field>
        </v-flex>
      </v-layout>
      <v-layout row>
        <v-flex xs4>
          <v-subheader>Membership ID</v-subheader>
        </v-flex>
        <v-flex xs8>
          <v-text-field
            :rules="numberRules"
            required
            v-model="account.agentId"
          ></v-text-field>
        </v-flex>
      </v-layout>
    </v-flex>

    <v-flex xs1></v-flex>

    <v-flex xs3>
      <div class="text-xs-center">
        <v-card>
          <v-card-title class="title">
            Profile Picture
          </v-card-title>
          <v-divider></v-divider>
          <v-card-text>
            <v-avatar tile size="200">
              <v-img
                :src="account.downloadURL"
                :lazy-src="userPlaceholder"
                v-if="account.downloadURL"
              >
                <v-layout
                  slot="placeholder"
                  fill-height
                  align-center
                  justify-center
                  ma-0
                >
                  <v-progress-circular
                    indeterminate
                    color="grey lighten-5"
                  ></v-progress-circular>
                </v-layout>
              </v-img>
              <v-img :src="userPlaceholder" :lazy-src="userPlaceholder" v-else>
                <v-layout
                  slot="placeholder"
                  fill-height
                  align-center
                  justify-center
                  ma-0
                >
                  <v-progress-circular
                    indeterminate
                    color="grey lighten-5"
                  ></v-progress-circular>
                </v-layout>
              </v-img>
            </v-avatar>
          </v-card-text>
        </v-card>
        <div style="margin-bottom: 50px;"></div>
        <v-card>
          <v-card-title class="title">
            Proof of ID
          </v-card-title>
          <v-divider></v-divider>
          <v-card-text>
            <v-avatar tile size="200">
              <v-img
                :src="account.proofOfId"
                :lazy-src="userPlaceholder"
                v-if="account.proofOfId"
              >
                <v-layout
                  slot="placeholder"
                  fill-height
                  align-center
                  justify-center
                  ma-0
                >
                  <v-progress-circular
                    indeterminate
                    color="grey lighten-5"
                  ></v-progress-circular>
                </v-layout>
              </v-img>
              <v-img :src="userPlaceholder" :lazy-src="userPlaceholder" v-else>
                <v-layout
                  slot="placeholder"
                  fill-height
                  align-center
                  justify-center
                  ma-0
                >
                  <v-progress-circular
                    indeterminate
                    color="grey lighten-5"
                  ></v-progress-circular>
                </v-layout>
              </v-img>
            </v-avatar>
            <br />
            <v-btn @click="show" color="primary">
              Enlarge
            </v-btn>
          </v-card-text>
        </v-card>
      </div>
    </v-flex>
    <v-dialog v-model="dialog" max-width="600">
      <v-card>
        <v-img
          :src="account.proofOfId"
          :lazy-src="userPlaceholder"
          contain
          v-if="account.proofOfId"
        >
          <v-layout
            slot="placeholder"
            fill-height
            align-center
            justify-center
            ma-0
          >
            <v-progress-circular
              indeterminate
              color="grey lighten-5"
            ></v-progress-circular>
          </v-layout>
        </v-img>
      </v-card>
    </v-dialog>
  </v-layout>
</template>

<script>
import userPlaceholder from "@/assets/placeholder.png";
import mixins from "@/mixins";
export default {
  props: ["account"],
  data: () => ({
    dialog: false
  }),
  computed: {
    userPlaceholder() {
      return userPlaceholder || "";
    }
  },
  mixins: [mixins],
  methods: {
    show() {
      this.dialog = true;
    }
  }
};
</script>
