<template>
  <v-container align-center justify-center>
    <v-layout align-center justify-center wrap row>
      <v-flex xs12>
        <v-card>
          <v-card-title>
            <v-layout align-center justify-start row wrap>
              <v-flex lg4 xs12>
                <div class="headline">Inventory Mangement</div>
              </v-flex>
              <v-flex lg6 offset-lg1 xs12>
                <v-text-field
                  v-model="search"
                  placeholder="search products..."
                  prepend-icon="search"
                  clearable
                ></v-text-field>
              </v-flex>
              <v-flex xs12 mt-1>
                <v-divider></v-divider>
              </v-flex>
            </v-layout>
          </v-card-title>
          
          <v-container>
            <v-data-table
              :headers="headers"
              :items="products"
              item-key="id"
              class="elevation-1"
              :search="search"
              :loading="loading"
              :rows-per-page-items="rowsPerPageItems"
              :pagination.sync="pagination"
            >
              <template slot="headerCell" slot-scope="props">
                <v-tooltip bottom max-width="150">
                  <template v-slot:activator="{ on }">
                    <span v-on="on">
                      {{ props.header.text }}
                    </span>
                  </template>
                  <span>
                    {{ props.header.description }}
                  </span>
                </v-tooltip>
              </template>

              <template slot="items" slot-scope="props">
                <tr 
                  :class="[ 
                    props.item.availableQTY <= props.item.reOrderLevel ? 'red lighten-3' : '',
                  ]"
                >
                  <td class="text-xs-left">{{props.item.name}}</td>
                  <td class="text-xs-left">{{props.item.category}}</td>
                  <td class="text-xs-center">{{props.item.onHandQTY}}</td>
                  <td class="text-xs-center">{{props.item.allocatedQTY}}</td>
                  <td class="text-xs-center">{{props.item.availableQTY}}</td>
                  <td class="text-xs-center">{{props.item.reOrderLevel}}</td>
                  <td class="pt-4">
                    <v-checkbox 
                      class="ml-4"
                      v-model="props.item.isOutOfStock"
                    ></v-checkbox>
                  </td>
                  <v-divider></v-divider>
                </tr>
              </template>
            </v-data-table>  
          </v-container>
        </v-card>
      </v-flex>
    </v-layout>
  </v-container>
</template>

<script>
import moment from 'moment';
import mixins from "@/mixins";
import { DB } from "@/config/firebase";

export default {
  mixins: [mixins],
  async mounted() {
    this.loading = true;
    this.lading = false;
    
  },
  data: () => ({
    loading: false,
    search: null,
    headers: [
      {
        text: 'Name', align: 'left', value: 'name',
        description: 'The name of the product.'
      },
      {
        text: 'Category', align:'left', value: 'category',
        description: 'The category to which the product is included.'
      },
      {
        text: 'QTY on Hand', align: 'center', value: 'onHandQTY',
        description: 
          'When you receive or produce inventory, add that number to this total. ' + 
          'When these items leave your warehouse, they are automatically subtracted.'
      },
      {
        text: 'QTY Allocated', align: 'center', value: 'allocatedQTY',
        description: 
        'This is the total number of your "QTY on Hand" inventory that have already been committed ' + 
        'to orders you have received from your Resellers.'
      },
      {
        text: 'QTY Available', align: 'center', value: 'availableQTY',
        description: 
          'This is the inventory you have available and ready for new orders from your Resellers. ' + 
          'This value is generated by subtracting "QTY Allocated" from "QTY on Hand."'
      },
      {
        text: 'Re-Order Notification Level', align: 'center', value: 'reOrderLevel',
        description: 
          'Use this field to set the number of "QTY Available" inventory at which you would like to be notified to order / ' +
          'produce more inventory for this product. When the "QTY Available" number counts down to the number you set, ' +
          'this product will rise to the top of the page and a red notification badge will appear on your menu list ' +
          'next to the "Inventory Management" title.'
      },
      {
        text: 'Out of Stock?', align: 'left', value: 'isOutOfStock',
        description: 'Tick this box, to mark a product as "Out of Stock". \n' + 
          'But this box is automatically ticked, once "QTY on Hand" is zero.'
      },
    ],

    pagination: {
      sortBy: 'availableQTY',
    },
    rowsPerPageItems: [10, 20, 50, {text: 'All', value: -1}],
  }),

  computed: {
    products() {
      const products = this.$store.getters['inventory/GET_ALL_PRODUCTS'];
      const modifiedProducts = products.map((product) => {
        const modifiedProduct = {
          id: product.id,
          name: product.name,
          category: product.category,
          onHandQTY: product.onHandQTY || 0,
          allocatedQTY: product.allocatedQTY || 0,
          availableQTY: product.availableQTY || 0,
          reOrderLevel: product.reOrderLevel || 0,
          isOutOfStock: product.isOutofStock,
        }
        return modifiedProduct;
      });
      return modifiedProducts;
    }
  },

  methods: {
    
  },

  watch: {
    products(val) {
      if(val.length < 5) {
        this.loading = true;
      
      } else this.loading = false;
    }
  },
}
</script>

<style>

</style>